# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regrec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
