# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regrec', '0003_add_verbose_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='comment',
        ),
        migrations.AddField(
            model_name='run',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='note'),
        ),
    ]
